package io.flutter.plugins;

import androidx.annotation.Keep;
import androidx.annotation.NonNull;
import io.flutter.Log;

import io.flutter.embedding.engine.FlutterEngine;

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
public final class GeneratedPluginRegistrant {
  private static final String TAG = "GeneratedPluginRegistrant";
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    try {
      flutterEngine.getPlugins().add(new io.flutter.plugins.camera.CameraPlugin());
    } catch(Exception e) {
      Log.e(TAG, "Error registering plugin camera, io.flutter.plugins.camera.CameraPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.nicodevelop.flutter_item_list.FlutterItemListPlugin());
    } catch(Exception e) {
      Log.e(TAG, "Error registering plugin flutter_item_list, com.nicodevelop.flutter_item_list.FlutterItemListPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.nicodevelop.flutter_mobile_camera.FlutterMobileCameraPlugin());
    } catch(Exception e) {
      Log.e(TAG, "Error registering plugin flutter_mobile_camera, com.nicodevelop.flutter_mobile_camera.FlutterMobileCameraPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.nicodevelop.flutter_profile_avatar.FlutterProfileAvatarPlugin());
    } catch(Exception e) {
      Log.e(TAG, "Error registering plugin flutter_profile_avatar, com.nicodevelop.flutter_profile_avatar.FlutterProfileAvatarPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.nicodevelop.flutter_profile_list.FlutterProfileListPlugin());
    } catch(Exception e) {
      Log.e(TAG, "Error registering plugin flutter_profile_list, com.nicodevelop.flutter_profile_list.FlutterProfileListPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new io.flutter.plugins.pathprovider.PathProviderPlugin());
    } catch(Exception e) {
      Log.e(TAG, "Error registering plugin path_provider, io.flutter.plugins.pathprovider.PathProviderPlugin", e);
    }
  }
}
